// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIslDR3VjoBl_K53ga1fbsadZ5gnQ_jGs',
    appId: '1:683955384516:web:4697a5b8a10184386a9991',
    messagingSenderId: '683955384516',
    projectId: 'ourproject-460ab',
    authDomain: 'ourproject-460ab.firebaseapp.com',
    storageBucket: 'ourproject-460ab.firebasestorage.app',
    measurementId: 'G-QE7BEVGTZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxSIv8G78x5I6en6-cbqI0DxlcKBagrjo',
    appId: '1:683955384516:android:f9530e86af2359406a9991',
    messagingSenderId: '683955384516',
    projectId: 'ourproject-460ab',
    storageBucket: 'ourproject-460ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONxo-d6bHId5yN4MRoqVcvfzHQrLhSdE',
    appId: '1:683955384516:ios:f2cf35dfe492af9e6a9991',
    messagingSenderId: '683955384516',
    projectId: 'ourproject-460ab',
    storageBucket: 'ourproject-460ab.firebasestorage.app',
    iosClientId: '683955384516-nv1n7fm17996fb7ssmt8p2acik2213vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.owerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONxo-d6bHId5yN4MRoqVcvfzHQrLhSdE',
    appId: '1:683955384516:ios:f2cf35dfe492af9e6a9991',
    messagingSenderId: '683955384516',
    projectId: 'ourproject-460ab',
    storageBucket: 'ourproject-460ab.firebasestorage.app',
    iosClientId: '683955384516-nv1n7fm17996fb7ssmt8p2acik2213vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.owerProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIslDR3VjoBl_K53ga1fbsadZ5gnQ_jGs',
    appId: '1:683955384516:web:013476ddd5878ce46a9991',
    messagingSenderId: '683955384516',
    projectId: 'ourproject-460ab',
    authDomain: 'ourproject-460ab.firebaseapp.com',
    storageBucket: 'ourproject-460ab.firebasestorage.app',
    measurementId: 'G-0PD2HEZ9LC',
  );

}